### PR TITLE
Fix progress bar still capturing stderr after exception

### LINKED ISSUE #15: Unknown exceptions are not displayed when progress bar is used
It looks like when an unknown exception is caught, the stderr wrapper is still active and the logs are hidden.

### LINKED ISSUE #22: Add percentage in progress bar
This data is missing.

### PR DESCRIPTION
**Pull request by Neraste**
Fixes #15, fixes #22.

### CODE REVIEW

**Review by Nadeflore — APPROVED** [review]
I remember this issue, so using a context manager should solve the problem.
Didn't test it, but it makes sense.

**Comment by Neraste** [comment]
I would like to open an issue on the progress bar repository.

**Comment by Neraste** [comment]
Looks like a [similar issue](https://github.com/WoLpH/python-progressbar/issues/212) was submitted, and that the progress bar can be already used as a context manager to prevent the problem. So this PR is redundant, but not the final use of the different progress bars. I will check that and adapt the code.

**Comment by Neraste** [comment]
I adapted the code, it is better to used the already provided secure mechanism.

**Review by Nadeflore — APPROVED** [review]

**Pull request merged**
