### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by odrling**
`dakara-base` didn't work fine with Python 3.12 due to using `distutils.util.strtobool` internally.
This PR fixes that by reimplementing the function [as is suggested in PEP 632](https://peps.python.org/pep-0632/).

The project now uses a `pyproject.toml` instead of the previous `setup.cfg` file. It should be equivalent to the previous configuration and work ootb with Python 3.12.

I've replaced usages of the `path` library with stdlib pathlib/shutil which is available in all supported versions.

I've reimplemented the [CI with Github Actions](https://github.com/odrling/dakara-base/actions/runs/7228852608), AFAIK it is equivalent to the previous Appveyor configuration and should work great out of the box. It only requires to set the Codecov token as an secret environment variable (`CODECOV_TOKEN`) in the repository settings.

I've replaced uses of flake8 in the project with ruff, which is a faster reimplementation of flake8 (and a few other Python dev tools). I've also selected a few more checks in ruff than what used to be checked by the previous configuration, notably Bugbear which returned an error that was fixed in 5e233eb5292019591a9af19fb1d8b93614f987b6.

Also drops Python 3.7 which is now EOL.

### CODE REVIEW

**Comment by Neraste** [comment]
Hello, thank you warmly for all your work on Dakara! I won't gonna lie, the project is quite stale on my end, but I'm open to continue the development again if I see that other people are motivated.

Let me check your changes this weekend. First, why move from Appveyor to GitHub Actions? Also, sticking to `path.py` was a choice, given the fact that this lib has more features (but I'm open to discuss about it).

If you're related to N7, please contact me on the Japan7 discord with the same name.

**Comment by odrling** [comment]
> First, why move from Appveyor to GitHub Actions?

It seems a bit easier to use to run tests across platform, at least for this CI I didn't have to write any platform specific script. The tests can also run in parallel which makes it that much faster.

> Also, sticking to `path.py` was a choice

I was actually not aware of this lib and thought it was mostly used as a compatibility layer before noticing that the API was different from pathlib's. It seemed trivial to stick to the standard libraries and remove the dependency for this repository so I still went ahead with it.

> If you're related to N7, please contact me on the Japan7 discord with the same name.

Sure (with a slightly different name).

**Comment by odrling** [comment]
28349963d39cf68f9e8bce78150db4193c8ce008 fixes the typing of the AppDirsPath class when using pathlib.Path, it wasn't correct now that the methods didn't return an instance of `str`

**Comment by odrling** [comment]
closing in favor of more fine-grained PRs (#45 and #46 for now)

**Pull request closed without merging**
